// (modrm is outside 00h - BFh) (mod != 11)
opcode_t FPU_mem[8*8] = { 
// D8
{ "fadds",	Md,__,__ },
{ "fmuls",	Md,__,__ },
{ "fcoms",	Md,__,__ },
{ "fcomps",	Md,__,__ },
{ "fsubs",	Md,__,__ },
{ "fsubrs",	Md,__,__ },
{ "fdivs",	Md,__,__ },
{ "fdivrs",	Md,__,__ },
// D9
{ "flds",	Md,__,__ },
{ "(bad)",	__,__,__ },
{ "fsts",	Md,__,__ },
{ "fstps",	Md,__,__ },
{ "fldenv",	__,__,__ },
{ "fldcw",	__,__,__ },
{ "fnstenv",	__,__,__ },
{ "fnstcw",	__,__,__ },
// DA
{ "fiaddl",	Md,__,__ },
{ "fimull",	Md,__,__ },
{ "ficoml",	Md,__,__ },
{ "ficompl",	Md,__,__ },
{ "fisubl",	Md,__,__ },
{ "fisubrl",	Md,__,__ },
{ "fidivl",	Md,__,__ },
{ "fidivrl",	Md,__,__ },
// DB
{ "fildl",	Md,__,__ },
{ "fisttpl",	Md,__,__ },
{ "fistl",	Md,__,__ },
{ "fistpl",	Md,__,__ },
{ "(bad)",	__,__,__ },
{ "fldt",	Mt,__,__ },
{ "(bad)",	__,__,__ },
{ "fstpt",	Mt,__,__ },
// DC
{ "faddl",	Mq,__,__ },
{ "fmull",	Mq,__,__ },
{ "fcoml",	Mq,__,__ },
{ "fcompl",	Mq,__,__ },
{ "fsubl",	Mq,__,__ },
{ "fsubrl",	Mq,__,__ },
{ "fdivl",	Mq,__,__ },
{ "fdivrl",	Mq,__,__ },
// DD
{ "fldl",	Mq,__,__ },
{ "fisttpq",	Mq,__,__ },
{ "fstl",	Mq,__,__ },
{ "fstpl",	Mq,__,__ },
{ "frstor",	__,__,__ },
{ "(bad)",	__,__,__ },
{ "fnsave",	__,__,__ },
{ "fnstsw",	__,__,__ },
// DE
{ "fiadds",	Mw,__,__ },
{ "fimuls",	Mw,__,__ },
{ "ficoms",	Mw,__,__ },
{ "ficomps",	Mw,__,__ },
{ "fisubs",	Mw,__,__ },
{ "fisubrs",	Mw,__,__ },
{ "fidivs",	Mw,__,__ },
{ "fidivrs",	Mw,__,__ },
// DF
{ "filds",	Mw,__,__ },
{ "fisttps",	Mw,__,__ },
{ "fists",	Mw,__,__ },
{ "fistps",	Mw,__,__ },
{ "fbldt",	Mt,__,__ },
{ "fildq",	Mq,__,__ },
{ "fbstpt",	Mt,__,__ },
{ "fistpq",	Mq,__,__ }
};

opcode_t FPU_reg[8*8*8] = {
/* D8 C0 */ { "fadd",	ST0,STi,__ },
/* D8 C1 */ { "fadd",	ST0,STi,__ },
/* D8 C2 */ { "fadd",	ST0,STi,__ },
/* D8 C3 */ { "fadd",	ST0,STi,__ },
/* D8 C4 */ { "fadd",	ST0,STi,__ },
/* D8 C5 */ { "fadd",	ST0,STi,__ },
/* D8 C6 */ { "fadd",	ST0,STi,__ },
/* D8 C7 */ { "fadd",	ST0,STi,__ },
/* D8 C8 */ { "fmul",	ST0,STi,__ },
/* D8 C9 */ { "fmul",	ST0,STi,__ },
/* D8 CA */ { "fmul",	ST0,STi,__ },
/* D8 CB */ { "fmul",	ST0,STi,__ },
/* D8 CC */ { "fmul",	ST0,STi,__ },
/* D8 CD */ { "fmul",	ST0,STi,__ },
/* D8 CE */ { "fmul",	ST0,STi,__ },
/* D8 CF */ { "fmul",	ST0,STi,__ },
/* D8 D0 */ { "fcom",	STi,__,__ },
/* D8 D1 */ { "fcom",	STi,__,__ },
/* D8 D2 */ { "fcom",	STi,__,__ },
/* D8 D3 */ { "fcom",	STi,__,__ },
/* D8 D4 */ { "fcom",	STi,__,__ },
/* D8 D5 */ { "fcom",	STi,__,__ },
/* D8 D6 */ { "fcom",	STi,__,__ },
/* D8 D7 */ { "fcom",	STi,__,__ },
/* D8 D8 */ { "fcomp",	STi,__,__ },
/* D8 D9 */ { "fcomp",	STi,__,__ },
/* D8 DA */ { "fcomp",	STi,__,__ },
/* D8 DB */ { "fcomp",	STi,__,__ },
/* D8 DC */ { "fcomp",	STi,__,__ },
/* D8 DD */ { "fcomp",	STi,__,__ },
/* D8 DE */ { "fcomp",	STi,__,__ },
/* D8 DF */ { "fcomp",	STi,__,__ },
/* D8 E0 */ { "fsub",	ST0,STi,__ },
/* D8 E1 */ { "fsub",	ST0,STi,__ },
/* D8 E2 */ { "fsub",	ST0,STi,__ },
/* D8 E3 */ { "fsub",	ST0,STi,__ },
/* D8 E4 */ { "fsub",	ST0,STi,__ },
/* D8 E5 */ { "fsub",	ST0,STi,__ },
/* D8 E6 */ { "fsub",	ST0,STi,__ },
/* D8 E7 */ { "fsub",	ST0,STi,__ },
/* D8 E8 */ { "fsubr",	ST0,STi,__ },
/* D8 E9 */ { "fsubr",	ST0,STi,__ },
/* D8 EA */ { "fsubr",	ST0,STi,__ },
/* D8 EB */ { "fsubr",	ST0,STi,__ },
/* D8 EC */ { "fsubr",	ST0,STi,__ },
/* D8 ED */ { "fsubr",	ST0,STi,__ },
/* D8 EE */ { "fsubr",	ST0,STi,__ },
/* D8 EF */ { "fsubr",	ST0,STi,__ },
/* D8 F0 */ { "fdiv",	ST0,STi,__ },
/* D8 F1 */ { "fdiv",	ST0,STi,__ },
/* D8 F2 */ { "fdiv",	ST0,STi,__ },
/* D8 F3 */ { "fdiv",	ST0,STi,__ },
/* D8 F4 */ { "fdiv",	ST0,STi,__ },
/* D8 F5 */ { "fdiv",	ST0,STi,__ },
/* D8 F6 */ { "fdiv",	ST0,STi,__ },
/* D8 F7 */ { "fdiv",	ST0,STi,__ },
/* D8 F8 */ { "fdivr",	ST0,STi,__ },
/* D8 F9 */ { "fdivr",	ST0,STi,__ },
/* D8 FA */ { "fdivr",	ST0,STi,__ },
/* D8 FB */ { "fdivr",	ST0,STi,__ },
/* D8 FC */ { "fdivr",	ST0,STi,__ },
/* D8 FD */ { "fdivr",	ST0,STi,__ },
/* D8 FE */ { "fdivr",	ST0,STi,__ },
/* D8 FF */ { "fdivr",	ST0,STi,__ },
/* D9 C0 */ { "fld",	STi,__,__ },
/* D9 C1 */ { "fld",	STi,__,__ },
/* D9 C2 */ { "fld",	STi,__,__ },
/* D9 C3 */ { "fld",	STi,__,__ },
/* D9 C4 */ { "fld",	STi,__,__ },
/* D9 C5 */ { "fld",	STi,__,__ },
/* D9 C6 */ { "fld",	STi,__,__ },
/* D9 C7 */ { "fld",	STi,__,__ },
/* D9 C8 */ { "fxch",	__,__,__ },
/* D9 C9 */ { "fxch",	__,__,__ },
/* D9 CA */ { "fxch",	__,__,__ },
/* D9 CB */ { "fxch",	__,__,__ },
/* D9 CC */ { "fxch",	__,__,__ },
/* D9 CD */ { "fxch",	__,__,__ },
/* D9 CE */ { "fxch",	__,__,__ },
/* D9 CF */ { "fxch",	__,__,__ },
/* D9 D0 */ { "fnop",	__,__,__ },
/* D9 D1 */ { "(bad)",	__,__,__ },
/* D9 D2 */ { "(bad)",	__,__,__ },
/* D9 D3 */ { "(bad)",	__,__,__ },
/* D9 D4 */ { "(bad)",	__,__,__ },
/* D9 D5 */ { "(bad)",	__,__,__ },
/* D9 D6 */ { "(bad)",	__,__,__ },
/* D9 D7 */ { "(bad)",	__,__,__ },
/* D9 D8 */ { "(bad)",	__,__,__ },
/* D9 D9 */ { "(bad)",	__,__,__ },
/* D9 DA */ { "(bad)",	__,__,__ },
/* D9 DB */ { "(bad)",	__,__,__ },
/* D9 DC */ { "(bad)",	__,__,__ },
/* D9 DD */ { "(bad)",	__,__,__ },
/* D9 DE */ { "(bad)",	__,__,__ },
/* D9 DF */ { "(bad)",	__,__,__ },
/* D9 E0 */ { "fchs",	__,__,__ },
/* D9 E1 */ { "fabs",	__,__,__ },
/* D9 E2 */ { "(bad)",	__,__,__ },
/* D9 E3 */ { "(bad)",	__,__,__ },
/* D9 E4 */ { "ftst",	__,__,__ },
/* D9 E5 */ { "fxam",	__,__,__ },
/* D9 E6 */ { "(bad)",	__,__,__ },
/* D9 E7 */ { "(bad)",	__,__,__ },
/* D9 E8 */ { "fld1",	__,__,__ },
/* D9 E9 */ { "fldl2t",	__,__,__ },
/* D9 EA */ { "fldl2e",	__,__,__ },
/* D9 EB */ { "fldpi",	__,__,__ },
/* D9 EC */ { "fldlg2",	__,__,__ },
/* D9 ED */ { "fldln2",	__,__,__ },
/* D9 EE */ { "fldz",	__,__,__ },
/* D9 EF */ { "(bad)",	__,__,__ },
/* D9 F0 */ { "f2xm1",	__,__,__ },
/* D9 F1 */ { "fyl2x",	__,__,__ },
/* D9 F2 */ { "fptan",	__,__,__ },
/* D9 F3 */ { "fpatan",	__,__,__ },
/* D9 F4 */ { "fxtract",__,__,__ },
/* D9 F5 */ { "fprem1",	__,__,__ },
/* D9 F6 */ { "fdecstp",__,__,__ },
/* D9 F7 */ { "fincstp",__,__,__ },
/* D9 F8 */ { "fprem",	__,__,__ },
/* D9 F9 */ { "fyl2xp1",__,__,__ },
/* D9 FA */ { "fsqrt",	__,__,__ },
/* D9 FB */ { "fsincos",__,__,__ },
/* D9 FC */ { "frndint",__,__,__ },
/* D9 FD */ { "fscale", __,__,__ },
/* D9 FE */ { "fsin",	__,__,__},
/* D9 FF */ { "fcos",	__,__,__ },
/* DA C0 */ { "fcmovb",	ST0,STi,__ },
/* DA C1 */ { "fcmovb",	ST0,STi,__ },
/* DA C2 */ { "fcmovb",	ST0,STi,__ },
/* DA C3 */ { "fcmovb",	ST0,STi,__ },
/* DA C4 */ { "fcmovb",	ST0,STi,__ },
/* DA C5 */ { "fcmovb",	ST0,STi,__ },
/* DA C6 */ { "fcmovb",	ST0,STi,__ },
/* DA C7 */ { "fcmovb",	ST0,STi,__ },
/* DA C8 */ { "fcmove",	ST0,STi,__ },
/* DA C9 */ { "fcmove",	ST0,STi,__ },
/* DA CA */ { "fcmove",	ST0,STi,__ },
/* DA CB */ { "fcmove",	ST0,STi,__ },
/* DA CC */ { "fcmove",	ST0,STi,__ },
/* DA CD */ { "fcmove",	ST0,STi,__ },
/* DA CE */ { "fcmove",	ST0,STi,__ },
/* DA CF */ { "fcmove",	ST0,STi,__ },
/* DA D0 */ { "fcmovbe",ST0,STi,__ },
/* DA D1 */ { "fcmovbe",ST0,STi,__ },
/* DA D2 */ { "fcmovbe",ST0,STi,__ },
/* DA D3 */ { "fcmovbe",ST0,STi,__ },
/* DA D4 */ { "fcmovbe",ST0,STi,__ },
/* DA D5 */ { "fcmovbe",ST0,STi,__ },
/* DA D6 */ { "fcmovbe",ST0,STi,__ },
/* DA D7 */ { "fcmovbe",ST0,STi,__ },
/* DA D8 */ { "fcmovu",	ST0,STi,__ },
/* DA D9 */ { "fcmovu",	ST0,STi,__ },
/* DA DA */ { "fcmovu",	ST0,STi,__ },
/* DA DB */ { "fcmovu",	ST0,STi,__ },
/* DA DC */ { "fcmovu",	ST0,STi,__ },
/* DA DD */ { "fcmovu",	ST0,STi,__ },
/* DA DE */ { "fcmovu",	ST0,STi,__ },
/* DA DF */ { "fcmovu",	ST0,STi,__ },
/* DA E0 */ { "(bad)",	__,__,__ },
/* DA E1 */ { "(bad)",	__,__,__ },
/* DA E2 */ { "(bad)",	__,__,__ },
/* DA E3 */ { "(bad)",	__,__,__ },
/* DA E4 */ { "(bad)",	__,__,__ },
/* DA E5 */ { "(bad)",	__,__,__ },
/* DA E6 */ { "(bad)",	__,__,__ },
/* DA E7 */ { "(bad)",	__,__,__ },
/* DA E8 */ { "(bad)",	__,__,__ },
/* DA E9 */ { "fucompp",__,__,__ },
/* DA EA */ { "(bad)",	__,__,__ },
/* DA EB */ { "(bad)",	__,__,__ },
/* DA EC */ { "(bad)",	__,__,__ },
/* DA ED */ { "(bad)",	__,__,__ },
/* DA EE */ { "(bad)",	__,__,__ },
/* DA EF */ { "(bad)",	__,__,__ },
/* DA F0 */ { "(bad)",	__,__,__ },
/* DA F1 */ { "(bad)",	__,__,__ },
/* DA F2 */ { "(bad)",	__,__,__ },
/* DA F3 */ { "(bad)",	__,__,__ },
/* DA F4 */ { "(bad)",	__,__,__ },
/* DA F5 */ { "(bad)",	__,__,__ },
/* DA F6 */ { "(bad)",	__,__,__ },
/* DA F7 */ { "(bad)",	__,__,__ },
/* DA F8 */ { "(bad)",	__,__,__ },
/* DA F9 */ { "(bad)",	__,__,__ },
/* DA FA */ { "(bad)",	__,__,__ },
/* DA FB */ { "(bad)",	__,__,__ },
/* DA FC */ { "(bad)",	__,__,__ },
/* DA FD */ { "(bad)",	__,__,__ },
/* DA FE */ { "(bad)",	__,__,__ },
/* DA FF */ { "(bad)",	__,__,__ },
/* DB C0 */ { "fcmovnb",ST0,STi,__ },
/* DB C1 */ { "fcmovnb",ST0,STi,__ },
/* DB C2 */ { "fcmovnb",ST0,STi,__ },
/* DB C3 */ { "fcmovnb",ST0,STi,__ },
/* DB C4 */ { "fcmovnb",ST0,STi,__ },
/* DB C5 */ { "fcmovnb",ST0,STi,__ },
/* DB C6 */ { "fcmovnb",ST0,STi,__ },
/* DB C7 */ { "fcmovnb",ST0,STi,__ },
/* DB C8 */ { "fcmovne",ST0,STi,__ },
/* DB C9 */ { "fcmovne",ST0,STi,__ },
/* DB CA */ { "fcmovne",ST0,STi,__ },
/* DB CB */ { "fcmovne",ST0,STi,__ },
/* DB CC */ { "fcmovne",ST0,STi,__ },
/* DB CD */ { "fcmovne",ST0,STi,__ },
/* DB CE */ { "fcmovne",ST0,STi,__ },
/* DB CF */ { "fcmovne",ST0,STi,__ },
/* DB D0 */ { "fcmovnbe",ST0,STi,__ },
/* DB D1 */ { "fcmovnbe",ST0,STi,__ },
/* DB D2 */ { "fcmovnbe",ST0,STi,__ },
/* DB D3 */ { "fcmovnbe",ST0,STi,__ },
/* DB D4 */ { "fcmovnbe",ST0,STi,__ },
/* DB D5 */ { "fcmovnbe",ST0,STi,__ },
/* DB D6 */ { "fcmovnbe",ST0,STi,__ },
/* DB D7 */ { "fcmovnbe",ST0,STi,__ },
/* DB D8 */ { "fcmovnu",ST0,STi,__ },
/* DB D9 */ { "fcmovnu",ST0,STi,__ },
/* DB DA */ { "fcmovnu",ST0,STi,__ },
/* DB DB */ { "fcmovnu",ST0,STi,__ },
/* DB DC */ { "fcmovnu",ST0,STi,__ },
/* DB DD */ { "fcmovnu",ST0,STi,__ },
/* DB DE */ { "fcmovnu",ST0,STi,__ },
/* DB DF */ { "fcmovnu",ST0,STi,__ },
/* DB E0 */ { "feni",	__,__,__ },
/* DB E1 */ { "fdisi",	__,__,__ },
/* DB E2 */ { "fnclex",	__,__,__ },
/* DB E3 */ { "fninit",	__,__,__ },
/* DB E4 */ { "fsetpm",	__,__,__ },
/* DB E5 */ { "(bad)",	__,__,__ },
/* DB E6 */ { "(bad)",	__,__,__ },
/* DB E7 */ { "(bad)",	__,__,__ },
/* DB E8 */ { "fucomi",	ST0,STi,__ },
/* DB E9 */ { "fucomi",	ST0,STi,__ },
/* DB EA */ { "fucomi",	ST0,STi,__ },
/* DB EB */ { "fucomi",	ST0,STi,__ },
/* DB EC */ { "fucomi",	ST0,STi,__ },
/* DB ED */ { "fucomi",	ST0,STi,__ },
/* DB EE */ { "fucomi",	ST0,STi,__ },
/* DB EF */ { "fucomi",	ST0,STi,__ },
/* DB F0 */ { "fcomi",	ST0,STi,__ },
/* DB F1 */ { "fcomi",	ST0,STi,__ },
/* DB F2 */ { "fcomi",	ST0,STi,__ },
/* DB F3 */ { "fcomi",	ST0,STi,__ },
/* DB F4 */ { "fcomi",	ST0,STi,__ },
/* DB F5 */ { "fcomi",	ST0,STi,__ },
/* DB F6 */ { "fcomi",	ST0,STi,__ },
/* DB F7 */ { "fcomi",	ST0,STi,__ },
/* DB F8 */ { "(bad)",	__,__,__ },
/* DB F9 */ { "(bad)",	__,__,__ },
/* DB FA */ { "(bad)",	__,__,__ },
/* DB FB */ { "(bad)",	__,__,__ },
/* DB FC */ { "(bad)",	__,__,__ },
/* DB FD */ { "(bad)",	__,__,__ },
/* DB FE */ { "(bad)",	__,__,__ },
/* DB FF */ { "(bad)",	__,__,__ },
/* DC C0 */ { "fadd",	STi,ST0,__ },
/* DC C1 */ { "fadd",	STi,ST0,__ },
/* DC C2 */ { "fadd",	STi,ST0,__ },
/* DC C3 */ { "fadd",	STi,ST0,__ },
/* DC C4 */ { "fadd",	STi,ST0,__ },
/* DC C5 */ { "fadd",	STi,ST0,__ },
/* DC C6 */ { "fadd",	STi,ST0,__ },
/* DC C7 */ { "fadd",	STi,ST0,__ },
/* DC C8 */ { "fmul",	STi,ST0,__ },
/* DC C9 */ { "fmul",	STi,ST0,__ },
/* DC CA */ { "fmul",	STi,ST0,__ },
/* DC CB */ { "fmul",	STi,ST0,__ },
/* DC CC */ { "fmul",	STi,ST0,__ },
/* DC CD */ { "fmul",	STi,ST0,__ },
/* DC CE */ { "fmul",	STi,ST0,__ },
/* DC CF */ { "fmul",	STi,ST0,__ },
/* DC D0 */ { "(bad)",	__,__,__ },
/* DC D1 */ { "(bad)",	__,__,__ },
/* DC D2 */ { "(bad)",	__,__,__ },
/* DC D3 */ { "(bad)",	__,__,__ },
/* DC D4 */ { "(bad)",	__,__,__ },
/* DC D5 */ { "(bad)",	__,__,__ },
/* DC D6 */ { "(bad)",	__,__,__ },
/* DC D7 */ { "(bad)",	__,__,__ },
/* DC D8 */ { "(bad)",	__,__,__ },
/* DC D9 */ { "(bad)",	__,__,__ },
/* DC DA */ { "(bad)",	__,__,__ },
/* DC DB */ { "(bad)",	__,__,__ },
/* DC DC */ { "(bad)",	__,__,__ },
/* DC DD */ { "(bad)",	__,__,__ },
/* DC DE */ { "(bad)",	__,__,__ },
/* DC DF */ { "(bad)",	__,__,__ },
/* DC E0 */ { "fsubr",	STi,ST0,__ },
/* DC E1 */ { "fsubr",	STi,ST0,__ },
/* DC E2 */ { "fsubr",	STi,ST0,__ },
/* DC E3 */ { "fsubr",	STi,ST0,__ },
/* DC E4 */ { "fsubr",	STi,ST0,__ },
/* DC E5 */ { "fsubr",	STi,ST0,__ },
/* DC E6 */ { "fsubr",	STi,ST0,__ },
/* DC E7 */ { "fsubr",	STi,ST0,__ },
/* DC E8 */ { "fsub",	STi,ST0,__ },
/* DC E9 */ { "fsub",	STi,ST0,__ },
/* DC EA */ { "fsub",	STi,ST0,__ },
/* DC EB */ { "fsub",	STi,ST0,__ },
/* DC EC */ { "fsub",	STi,ST0,__ },
/* DC ED */ { "fsub",	STi,ST0,__ },
/* DC EE */ { "fsub",	STi,ST0,__ },
/* DC EF */ { "fsub",	STi,ST0,__ },
/* DC F0 */ { "fdivr",	STi,ST0,__ },
/* DC F1 */ { "fdivr",	STi,ST0,__ },
/* DC F2 */ { "fdivr",	STi,ST0,__ },
/* DC F3 */ { "fdivr",	STi,ST0,__ },
/* DC F4 */ { "fdivr",	STi,ST0,__ },
/* DC F5 */ { "fdivr",	STi,ST0,__ },
/* DC F6 */ { "fdivr",	STi,ST0,__ },
/* DC F7 */ { "fdivr",	STi,ST0,__ },
/* DC F8 */ { "fdiv",	STi,ST0,__ },
/* DC F9 */ { "fdiv",	STi,ST0,__ },
/* DC FA */ { "fdiv",	STi,ST0,__ },
/* DC FB */ { "fdiv",	STi,ST0,__ },
/* DC FC */ { "fdiv",	STi,ST0,__ },
/* DC FD */ { "fdiv",	STi,ST0,__ },
/* DC FE */ { "fdiv",	STi,ST0,__ },
/* DC FF */ { "fdiv",	STi,ST0,__ },
/* DD C0 */ { "ffree",	STi,__,__ },
/* DD C1 */ { "ffree",	STi,__,__ },
/* DD C2 */ { "ffree",	STi,__,__ },
/* DD C3 */ { "ffree",	STi,__,__ },
/* DD C4 */ { "ffree",	STi,__,__ },
/* DD C5 */ { "ffree",	STi,__,__ },
/* DD C6 */ { "ffree",	STi,__,__ },
/* DD C7 */ { "ffree",	STi,__,__ },
/* DD C8 */ { "(bad)",	__,__,__ },
/* DD C9 */ { "(bad)",	__,__,__ },
/* DD CA */ { "(bad)",	__,__,__ },
/* DD CB */ { "(bad)",	__,__,__ },
/* DD CC */ { "(bad)",	__,__,__ },
/* DD CD */ { "(bad)",	__,__,__ },
/* DD CE */ { "(bad)",	__,__,__ },
/* DD CF */ { "(bad)",	__,__,__ },
/* DD D0 */ { "fst",	STi,__,__ },
/* DD D1 */ { "fst",	STi,__,__ },
/* DD D2 */ { "fst",	STi,__,__ },
/* DD D3 */ { "fst",	STi,__,__ },
/* DD D4 */ { "fst",	STi,__,__ },
/* DD D5 */ { "fst",	STi,__,__ },
/* DD D6 */ { "fst",	STi,__,__ },
/* DD D7 */ { "fst",	STi,__,__ },
/* DD D8 */ { "fstp",	STi,__,__ },
/* DD D9 */ { "fstp",	STi,__,__ },
/* DD DA */ { "fstp",	STi,__,__ },
/* DD DB */ { "fstp",	STi,__,__ },
/* DD DC */ { "fstp",	STi,__,__ },
/* DD DD */ { "fstp",	STi,__,__ },
/* DD DE */ { "fstp",	STi,__,__ },
/* DD DF */ { "fstp",	STi,__,__ },
/* DD E0 */ { "fucom",	STi,__,__ },
/* DD E1 */ { "fucom",	STi,__,__ },
/* DD E2 */ { "fucom",	STi,__,__ },
/* DD E3 */ { "fucom",	STi,__,__ },
/* DD E4 */ { "fucom",	STi,__,__ },
/* DD E5 */ { "fucom",	STi,__,__ },
/* DD E6 */ { "fucom",	STi,__,__ },
/* DD E7 */ { "fucom",	STi,__,__ },
/* DD E8 */ { "fucomp",	STi,__,__ },
/* DD E9 */ { "fucomp",	STi,__,__ },
/* DD EA */ { "fucomp",	STi,__,__ },
/* DD EB */ { "fucomp",	STi,__,__ },
/* DD EC */ { "fucomp",	STi,__,__ },
/* DD ED */ { "fucomp",	STi,__,__ },
/* DD EE */ { "fucomp",	STi,__,__ },
/* DD EF */ { "fucomp",	STi,__,__ },
/* DD F0 */ { "(bad)",	__,__,__ },
/* DD F1 */ { "(bad)",	__,__,__ },
/* DD F2 */ { "(bad)",	__,__,__ },
/* DD F3 */ { "(bad)",	__,__,__ },
/* DD F4 */ { "(bad)",	__,__,__ },
/* DD F5 */ { "(bad)",	__,__,__ },
/* DD F6 */ { "(bad)",	__,__,__ },
/* DD F7 */ { "(bad)",	__,__,__ },
/* DD F8 */ { "(bad)",	__,__,__ },
/* DD F9 */ { "(bad)",	__,__,__ },
/* DD FA */ { "(bad)",	__,__,__ },
/* DD FB */ { "(bad)",	__,__,__ },
/* DD FC */ { "(bad)",	__,__,__ },
/* DD FD */ { "(bad)",	__,__,__ },
/* DD FE */ { "(bad)",	__,__,__ },
/* DD FF */ { "(bad)",	__,__,__ },
/* DE C0 */ { "faddp",	STi,ST0,__ },
/* DE C1 */ { "faddp",	STi,ST0,__ },
/* DE C2 */ { "faddp",	STi,ST0,__ },
/* DE C3 */ { "faddp",	STi,ST0,__ },
/* DE C4 */ { "faddp",	STi,ST0,__ },
/* DE C5 */ { "faddp",	STi,ST0,__ },
/* DE C6 */ { "faddp",	STi,ST0,__ },
/* DE C7 */ { "faddp",	STi,ST0,__ },
/* DE C8 */ { "fmulp",	STi,ST0,__ },
/* DE C9 */ { "fmulp",	STi,ST0,__ },
/* DE CA */ { "fmulp",	STi,ST0,__ },
/* DE CB */ { "fmulp",	STi,ST0,__ },
/* DE CC */ { "fmulp",	STi,ST0,__ },
/* DE CD */ { "fmulp",	STi,ST0,__ },
/* DE CE */ { "fmulp",	STi,ST0,__ },
/* DE CF */ { "fmulp",	STi,ST0,__ },
/* DE D0 */ { "(bad)",	__,__,__ },
/* DE D1 */ { "(bad)",	__,__,__ },
/* DE D2 */ { "(bad)",	__,__,__ },
/* DE D3 */ { "(bad)",	__,__,__ },
/* DE D4 */ { "(bad)",	__,__,__ },
/* DE D5 */ { "(bad)",	__,__,__ },
/* DE D6 */ { "(bad)",	__,__,__ },
/* DE D7 */ { "(bad)",	__,__,__ },
/* DE D8 */ { "(bad)",	__,__,__ },
/* DE D9 */ { "fcompp",	__,__,__ },
/* DE DA */ { "(bad)",	__,__,__ },
/* DE DB */ { "(bad)",	__,__,__ },
/* DE DC */ { "(bad)",	__,__,__ },
/* DE DD */ { "(bad)",	__,__,__ },
/* DE DE */ { "(bad)",	__,__,__ },
/* DE DF */ { "(bad)",	__,__,__ },
/* DE E0 */ { "fsubrp",	STi,ST0,__ },
/* DE E1 */ { "fsubrp",	STi,ST0,__ },
/* DE E2 */ { "fsubrp",	STi,ST0,__ },
/* DE E3 */ { "fsubrp",	STi,ST0,__ },
/* DE E4 */ { "fsubrp",	STi,ST0,__ },
/* DE E5 */ { "fsubrp",	STi,ST0,__ },
/* DE E6 */ { "fsubrp",	STi,ST0,__ },
/* DE E7 */ { "fsubrp",	STi,ST0,__ },
/* DE E8 */ { "fsubp",	STi,ST0,__ },
/* DE E9 */ { "fsubp",	STi,ST0,__ },
/* DE EA */ { "fsubp",	STi,ST0,__ },
/* DE EB */ { "fsubp",	STi,ST0,__ },
/* DE EC */ { "fsubp",	STi,ST0,__ },
/* DE ED */ { "fsubp",	STi,ST0,__ },
/* DE EE */ { "fsubp",	STi,ST0,__ },
/* DE EF */ { "fsubp",	STi,ST0,__ },
/* DE F0 */ { "fdivrp",	STi,ST0,__ },
/* DE F1 */ { "fdivrp",	STi,ST0,__ },
/* DE F2 */ { "fdivrp",	STi,ST0,__ },
/* DE F3 */ { "fdivrp",	STi,ST0,__ },
/* DE F4 */ { "fdivrp",	STi,ST0,__ },
/* DE F5 */ { "fdivrp",	STi,ST0,__ },
/* DE F6 */ { "fdivrp",	STi,ST0,__ },
/* DE F7 */ { "fdivrp",	STi,ST0,__ },
/* DE F8 */ { "fdivp",	STi,ST0,__ },
/* DE F9 */ { "fdivp",	STi,ST0,__ },
/* DE FA */ { "fdivp",	STi,ST0,__ },
/* DE FB */ { "fdivp",	STi,ST0,__ },
/* DE FC */ { "fdivp",	STi,ST0,__ },
/* DE FD */ { "fdivp",	STi,ST0,__ },
/* DE FE */ { "fdivp",	STi,ST0,__ },
/* DE FF */ { "fdivp",	STi,ST0,__ },
/* DF C0 */ { "ffreep",	STi,__,__ }, // 287 compatibility opcode
/* DF C1 */ { "ffreep",	STi,__,__ },
/* DF C2 */ { "ffreep",	STi,__,__ },
/* DF C3 */ { "ffreep",	STi,__,__ },
/* DF C4 */ { "ffreep",	STi,__,__ },
/* DF C5 */ { "ffreep",	STi,__,__ },
/* DF C6 */ { "ffreep",	STi,__,__ },
/* DF C7 */ { "ffreep",	STi,__,__ },
/* DF C8 */ { "(bad)",	__,__,__ },
/* DF C9 */ { "(bad)",	__,__,__ },
/* DF CA */ { "(bad)",	__,__,__ },
/* DF CB */ { "(bad)",	__,__,__ },
/* DF CC */ { "(bad)",	__,__,__ },
/* DF CD */ { "(bad)",	__,__,__ },
/* DF CE */ { "(bad)",	__,__,__ },
/* DF CF */ { "(bad)",	__,__,__ },
/* DF D0 */ { "(bad)",	__,__,__ },
/* DF D1 */ { "(bad)",	__,__,__ },
/* DF D2 */ { "(bad)",	__,__,__ },
/* DF D3 */ { "(bad)",	__,__,__ },
/* DF D4 */ { "(bad)",	__,__,__ },
/* DF D5 */ { "(bad)",	__,__,__ },
/* DF D6 */ { "(bad)",	__,__,__ },
/* DF D7 */ { "(bad)",	__,__,__ },
/* DF D8 */ { "(bad)",	__,__,__ },
/* DF D9 */ { "(bad)",	__,__,__ },
/* DF DA */ { "(bad)",	__,__,__ },
/* DF DB */ { "(bad)",	__,__,__ },
/* DF DC */ { "(bad)",	__,__,__ },
/* DF DD */ { "(bad)",	__,__,__ },
/* DF DE */ { "(bad)",	__,__,__ },
/* DF DF */ { "(bad)",	__,__,__ },
/* DF E0 */ { "fnstsw",	AX,__,__ },
/* DF E1 */ { "(bad)",	__,__,__ },
/* DF E2 */ { "(bad)",	__,__,__ },
/* DF E3 */ { "(bad)",	__,__,__ },
/* DF E4 */ { "(bad)",	__,__,__ },
/* DF E5 */ { "(bad)",	__,__,__ },
/* DF E6 */ { "(bad)",	__,__,__ },
/* DF E7 */ { "(bad)",	__,__,__ },
/* DF E8 */ { "fucomip",ST0,STi,__ },
/* DF E9 */ { "fucomip",ST0,STi,__ },
/* DF EA */ { "fucomip",ST0,STi,__ },
/* DF EB */ { "fucomip",ST0,STi,__ },
/* DF EC */ { "fucomip",ST0,STi,__ },
/* DF ED */ { "fucomip",ST0,STi,__ },
/* DF EE */ { "fucomip",ST0,STi,__ },
/* DF EF */ { "fucomip",ST0,STi,__ },
/* DF F0 */ { "fcomip",	ST0,STi,__ },
/* DF F1 */ { "fcomip",	ST0,STi,__ },
/* DF F2 */ { "fcomip",	ST0,STi,__ },
/* DF F3 */ { "fcomip",	ST0,STi,__ },
/* DF F4 */ { "fcomip",	ST0,STi,__ },
/* DF F5 */ { "fcomip",	ST0,STi,__ },
/* DF F6 */ { "fcomip",	ST0,STi,__ },
/* DF F7 */ { "fcomip",	ST0,STi,__ },
/* DF F8 */ { "(bad)",	__,__,__ },
/* DF F9 */ { "(bad)", __,__,__ },
/* DF FA */ { "(bad)", __,__,__ },
/* DF FB */ { "(bad)", __,__,__ },
/* DF FC */ { "(bad)", __,__,__ },
/* DF FD */ { "(bad)", __,__,__ },
/* DF FE */ { "(bad)", __,__,__ },
/* DF FF */ { "(bad)", __,__,__ },
};
