/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>
#include <unistd.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define YY_USES_REJECT
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
#define YY_FLEX_LEX_COMPAT
extern int yylineno;
int yylineno = 1;
extern char yytext[];


static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	if ( yyleng + yy_more_offset >= YYLMAX ) \
		YY_FATAL_ERROR( "token too large, exceeds YYLMAX" ); \
	yy_flex_strncpy( &yytext[yy_more_offset], yytext_ptr, yyleng + 1 ); \
	yyleng += yy_more_offset; \
	yy_prev_more_offset = yy_more_offset; \
	yy_more_offset = 0; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 75
#define YY_END_OF_BUFFER 76
static yyconst short int yy_acclist[253] =
    {   0,
       76,   75,    1,   75,   30,   75,   75,   75,   34,   75,
       21,   75,    6,   75,    7,   75,   14,   75,   12,   75,
       35,   75,   15,   75,   16,   75,   72,   75,   72,   75,
       13,   75,   36,   75,   24,   75,   26,   75,   23,   75,
        8,   75,    9,   75,   31,   75,   74,   75,   74,   75,
       74,   75,   74,   75,   74,   75,   74,   75,   74,   75,
       74,   75,   74,   75,   74,   75,   74,   75,   10,   75,
       22,   75,   11,   75,   27,    2,   20,   72,   17,   28,
       25,   29,   18,   74,   74,   74,   74,   74,   74,   74,
       74,   74,   74,   74,   74,   32,   74,   74,   74,   74,

       74,   74,   74,   74,   74,   19,    3,   73,   74,   74,
       74,   56,   74,   62,   74,   57,   74,   58,   74,   61,
       74,   59,   74,   74,   74,   60,   74,   63,   74,   74,
       74,   74,   74,   65,   74,   74,   74,   74,   74,    4,
        5,   74,   74,   33,   74,   74,   38,   74,   74,   37,
       74,   74,   74,   74,   74,   74,   74,   74,   66,   74,
       74,   74,   74,   74,   74,   74,   74,   74,   74,   74,
       74,   74,   74,   64,   74,   47,   74,   74,   74,   74,
       74,   74,   74,   74,   69,   74,   74,   74,   74,   74,
       74,   74,   74,   74,   42,   74,   46,   74,   48,   74,

       54,   74,   49,   74,   50,   74,   53,   74,   51,   74,
       52,   74,   55,   74,   74,   74,   74,   74,   74,   67,
       74,   71,   74,   74,   43,   74,   44,   74,   68,   74,
       70,   74,   74,   39,   74,   45,   74,   74,   74,   74,
       74,   74,   40,   74,   74,   74,   74,   74,   74,   74,
       41,   74
    } ;

static yyconst short int yy_accept[198] =
    {   0,
        1,    1,    1,    2,    3,    5,    7,    8,    9,   11,
       13,   15,   17,   19,   21,   23,   25,   27,   29,   31,
       33,   35,   37,   39,   41,   43,   45,   47,   49,   51,
       53,   55,   57,   59,   61,   63,   65,   67,   69,   71,
       73,   75,   76,   76,   77,   77,   78,   78,   78,   79,
       79,   80,   81,   82,   83,   84,   85,   86,   87,   88,
       89,   90,   91,   92,   93,   94,   95,   96,   98,   99,
      100,  101,  102,  103,  104,  105,  106,  107,  107,  107,
      107,  107,  108,  109,  110,  111,  112,  114,  116,  118,
      120,  122,  124,  125,  126,  128,  130,  131,  132,  133,

      134,  136,  137,  138,  139,  140,  141,  142,  143,  143,
      143,  144,  146,  147,  149,  150,  152,  153,  154,  155,
      156,  157,  158,  159,  159,  160,  161,  162,  163,  164,
      165,  166,  167,  168,  169,  170,  171,  172,  173,  174,
      176,  178,  179,  180,  181,  182,  183,  184,  185,  187,
      188,  189,  190,  191,  192,  193,  194,  195,  197,  199,
      201,  203,  205,  207,  209,  211,  213,  215,  216,  217,
      218,  219,  220,  222,  224,  225,  227,  229,  231,  233,
      234,  236,  238,  239,  240,  241,  242,  243,  245,  246,
      247,  248,  249,  250,  251,  253,  253

    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    7,    8,    9,    1,   10,
       11,   12,   13,   14,   15,    1,   16,   17,   18,   19,
       20,   21,   21,   22,   21,   23,   21,   24,   25,   26,
       27,   28,    1,    1,   33,   34,   35,   36,   37,   38,
       39,   40,   41,   42,   43,   44,   45,   46,   47,   48,
       42,   49,   50,   51,   52,   42,   53,   54,   55,   42,
       29,    1,   30,   31,   32,    1,   33,   34,   35,   36,

       37,   38,   39,   40,   41,   42,   43,   44,   45,   46,
       47,   48,   42,   49,   50,   51,   52,   42,   53,   54,
       55,   42,   56,   57,   58,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[59] =
    {   0,
        1,    1,    1,    1,    2,    1,    1,    1,    1,    1,
        3,    1,    1,    1,    1,    4,    5,    5,    5,    5,
        5,    5,    5,    1,    1,    1,    1,    1,    1,    1,
        1,    6,    5,    5,    5,    5,    5,    5,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    1,    1,    1
    } ;

static yyconst short int yy_base[204] =
    {   0,
        0,    0,  294,  295,  295,  266,  289,  281,  295,  281,
      295,  295,  295,  295,  295,  295,   47,   47,   54,  295,
      295,   34,  262,   51,  295,  295,  295,    0,   44,  251,
       49,  238,  248,   53,  248,   59,  251,  234,  295,  225,
      295,  295,  278,  295,    0,  295,  268,  276,   89,    0,
      295,  295,  295,  295,  295,    0,  229,  232,  238,  221,
       33,  220,   48,  223,  221,   49,  234,    0,  236,  234,
      223,  214,  227,  229,  223,  222,  295,  251,  249,  244,
      256,  295,    0,  221,  111,  224,    0,    0,    0,    0,
        0,    0,  219,  214,    0,    0,  217,  216,  209,  219,

        0,  209,   74,  205,  197,  295,  295,  197,  115,  188,
      193,    0,  207,   82,  199,    0,   63,  192,  195,  203,
      195,  201,  187,  178,  295,  184,  185,   99,  196,  195,
      119,  191,  184,  178,  177,  188,  189,  106,  188,    0,
        0,  170,   74,  169,   89,  103,  177,  182,    0,  187,
      178,  169,  135,  142,  181,  181,  182,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,  155,  162,  150,
      144,  133,    0,    0,  133,    0,    0,    0,    0,  129,
        0,    0,  129,  113,  113,  111,   97,    0,   90,   77,
       70,   66,   39,   39,    0,  295,  185,  187,  193,  199,

      205,   57,  211
    } ;

static yyconst short int yy_def[204] =
    {   0,
      196,    1,  196,  196,  196,  196,  197,  196,  196,  196,
      196,  196,  196,  196,  196,  196,  196,  196,  196,  196,
      196,  196,  196,  196,  196,  196,  196,  198,  198,  198,
      198,  198,  198,  198,  198,  198,  198,  198,  196,  196,
      196,  196,  197,  196,  199,  196,  200,  201,  196,  202,
      196,  196,  196,  196,  196,  198,  198,  198,  198,  198,
      198,  198,  198,  198,  198,  198,  198,  198,  198,  198,
      198,  198,  198,  198,  198,  198,  196,  199,  200,  196,
      201,  196,  202,  198,  198,  198,  198,  198,  198,  198,
      198,  198,  198,  198,  198,  198,  198,  198,  198,  198,

      198,  198,  198,  198,  198,  196,  196,  198,  196,  203,
      198,  198,  198,  198,  198,  198,  198,  198,  198,  198,
      198,  198,  198,  203,  196,  198,  198,  198,  198,  198,
      198,  198,  198,  198,  198,  198,  198,  198,  198,  198,
      198,  198,  198,  198,  198,  198,  198,  198,  198,  198,
      198,  198,  198,  198,  198,  198,  198,  198,  198,  198,
      198,  198,  198,  198,  198,  198,  198,  198,  198,  198,
      198,  198,  198,  198,  198,  198,  198,  198,  198,  198,
      198,  198,  198,  198,  198,  198,  198,  198,  198,  198,
      198,  198,  198,  198,  198,    0,  196,  196,  196,  196,

      196,  196,  196
    } ;

static yyconst short int yy_nxt[354] =
    {   0,
        4,    5,    5,    6,    4,    7,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   19,   19,
       19,   19,   19,   20,   21,   22,   23,   24,   25,   26,
       27,   28,   29,   28,   28,   30,   31,   32,   28,   28,
       33,   28,   28,   34,   35,   28,   28,   28,   36,   28,
       37,   28,   38,   28,   28,   39,   40,   41,   47,   51,
       52,   83,   48,   49,   49,   49,   49,   49,   49,   49,
       49,   49,   49,   49,   49,   49,   49,   54,   55,   57,
       88,   60,   61,   62,   63,   69,   89,  195,   91,   95,
      194,   72,   64,   58,   65,   73,   96,  132,   66,   70,

       50,   92,  193,  133,   74,   49,   49,   49,   49,   49,
       49,   49,  109,  109,  119,  109,  109,  109,  128,  109,
      192,  161,  120,  156,  191,  157,  129,  162,  158,  164,
      130,  142,  143,  144,  145,  149,  149,  149,  149,  149,
      149,  149,  165,  166,  190,  189,  188,  187,  146,  186,
      167,  173,  173,  173,  173,  173,  173,  173,  174,  174,
      174,  174,  174,  174,  174,  185,  110,  184,  183,  182,
      110,  178,  178,  178,  178,  178,  178,  178,  179,  179,
      179,  179,  179,  179,  179,   43,   43,   43,   43,   43,
       43,   56,   56,   78,  181,  180,   78,   78,   78,   79,

      177,   79,  176,   79,   79,   81,   81,   81,   81,   81,
       81,  124,  175,  124,  124,  124,  124,  172,  171,  170,
      169,  168,  163,  160,  159,  155,  154,  153,  152,  151,
      150,  148,  147,  141,  140,  125,  139,  138,  137,  136,
      135,  134,  131,  127,  126,  125,  123,  122,  121,  118,
      117,  116,  115,  114,  113,  112,  111,  108,   82,  107,
       80,  106,  105,  104,  103,  102,  101,  100,   99,   98,
       97,   94,   93,   90,   87,   86,   85,   84,   82,   80,
       44,   77,   76,   75,   71,   68,   67,   59,   53,   46,
       45,   44,   42,  196,    3,  196,  196,  196,  196,  196,

      196,  196,  196,  196,  196,  196,  196,  196,  196,  196,
      196,  196,  196,  196,  196,  196,  196,  196,  196,  196,
      196,  196,  196,  196,  196,  196,  196,  196,  196,  196,
      196,  196,  196,  196,  196,  196,  196,  196,  196,  196,
      196,  196,  196,  196,  196,  196,  196,  196,  196,  196,
      196,  196,  196
    } ;

static yyconst short int yy_chk[354] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,   17,   22,
       22,  202,   17,   18,   18,   18,   18,   18,   18,   18,
       19,   19,   19,   19,   19,   19,   19,   24,   24,   29,
       61,   31,   31,   31,   31,   34,   61,  194,   63,   66,
      193,   36,   31,   29,   31,   36,   66,  117,   31,   34,

       18,   63,  192,  117,   36,   49,   49,   49,   49,   49,
       49,   49,   85,   85,  103,   85,  109,  109,  114,  109,
      191,  143,  103,  138,  190,  138,  114,  143,  138,  145,
      114,  128,  128,  128,  128,  131,  131,  131,  131,  131,
      131,  131,  145,  146,  189,  187,  186,  185,  128,  184,
      146,  153,  153,  153,  153,  153,  153,  153,  154,  154,
      154,  154,  154,  154,  154,  183,   85,  180,  175,  172,
      109,  168,  168,  168,  168,  168,  168,  168,  169,  169,
      169,  169,  169,  169,  169,  197,  197,  197,  197,  197,
      197,  198,  198,  199,  171,  170,  199,  199,  199,  200,

      157,  200,  156,  200,  200,  201,  201,  201,  201,  201,
      201,  203,  155,  203,  203,  203,  203,  152,  151,  150,
      148,  147,  144,  142,  139,  137,  136,  135,  134,  133,
      132,  130,  129,  127,  126,  124,  123,  122,  121,  120,
      119,  118,  115,  113,  111,  110,  108,  105,  104,  102,
      100,   99,   98,   97,   94,   93,   86,   84,   81,   80,
       79,   78,   76,   75,   74,   73,   72,   71,   70,   69,
       67,   65,   64,   62,   60,   59,   58,   57,   48,   47,
       43,   40,   38,   37,   35,   33,   32,   30,   23,   10,
        8,    7,    6,    3,  196,  196,  196,  196,  196,  196,

      196,  196,  196,  196,  196,  196,  196,  196,  196,  196,
      196,  196,  196,  196,  196,  196,  196,  196,  196,  196,
      196,  196,  196,  196,  196,  196,  196,  196,  196,  196,
      196,  196,  196,  196,  196,  196,  196,  196,  196,  196,
      196,  196,  196,  196,  196,  196,  196,  196,  196,  196,
      196,  196,  196
    } ;

static yy_state_type yy_state_buf[YY_BUF_SIZE + 2], *yy_state_ptr;
static char *yy_full_match;
static int yy_lp;
#define REJECT \
{ \
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */ \
yy_cp = yy_full_match; /* restore poss. backed-over text */ \
++yy_lp; \
goto find_rule; \
}
static int yy_more_offset = 0;
static int yy_prev_more_offset = 0;
#define yymore() (yy_more_offset = yy_flex_strlen( yytext ))
#define YY_NEED_STRLEN
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET \
	{ \
	yy_more_offset = yy_prev_more_offset; \
	yyleng -= yy_more_offset; \
	}
#ifndef YYLMAX
#define YYLMAX 8192
#endif

char yytext[YYLMAX];
char *yytext_ptr;
#line 1 "kpasm.l"
#define INITIAL 0
#line 2 "kpasm.l"
#include <malloc.h>
#include <string.h>
#include "kpasm.h"
#include "kpasm.tab.h"


#define YY_INPUT(buf,result,max_size) \
{   \
   int c = getchar(); \
   /*if(c>='a' && c<='z') c+='A'-'a';*/ \
   result = (c == EOF) ? YY_NULL : (buf[0] = c, 1); \
}

#line 581 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp = NULL, *yy_bp = NULL;
	register int yy_act;

#line 17 "kpasm.l"


#line 735 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_state_ptr = yy_state_buf;
		*yy_state_ptr++ = yy_current_state;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 197 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			*yy_state_ptr++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 295 );

yy_find_action:
		yy_current_state = *--yy_state_ptr;
		yy_lp = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( yy_lp && yy_lp < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[yy_lp];
					{
					yy_full_match = yy_cp;
					break;
					}
				}
			--yy_cp;
			yy_current_state = *--yy_state_ptr;
			yy_lp = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					++yylineno;
			}

do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
YY_RULE_SETUP
#line 19 "kpasm.l"
;
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 20 "kpasm.l"
;
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 21 "kpasm.l"
;
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 22 "kpasm.l"
{
char* debext=strstr(yytext,"(")+1;
char* finext=strstr(yytext,")");
char* lext=(char*)malloc((finext-debext+2)*sizeof(char));
strncpy(lext,debext,finext-debext);
lext[finext-debext]='\0';
yylval.chaine=lext;
return(IDEXT);
};
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 31 "kpasm.l"
;
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 32 "kpasm.l"
return(PARENTHESE_OUVRANTE); 
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 33 "kpasm.l"
return(PARENTHESE_FERMANTE); 
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 34 "kpasm.l"
return(CROCHET_OUVRANT);
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 35 "kpasm.l"
return(CROCHET_FERMANT);
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 36 "kpasm.l"
return(ACCOLADE_OUVRANTE); 
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 37 "kpasm.l"
return(ACCOLADE_FERMANTE); 
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 38 "kpasm.l"
return(PLUS);
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 39 "kpasm.l"
return(DEUXPOINTS);
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 40 "kpasm.l"
return(MULT);
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 41 "kpasm.l"
return(MOINS);
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 42 "kpasm.l"
return(DIV);
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 43 "kpasm.l"
return(SHL);
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 44 "kpasm.l"
return(SHR);
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 45 "kpasm.l"
return(BOR);
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 46 "kpasm.l"
return(BAND);
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 47 "kpasm.l"
return(AND);
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 48 "kpasm.l"
return(OR);
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 49 "kpasm.l"
return(SUP);
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 50 "kpasm.l"
return(INF);
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 51 "kpasm.l"
return(EGAL);
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 52 "kpasm.l"
return(EGAL);
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 53 "kpasm.l"
return(PASEGAL);
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 54 "kpasm.l"
return(INFOUEGAL);
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 55 "kpasm.l"
return(SUPOUEGAL);
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 56 "kpasm.l"
return(NOT);
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 57 "kpasm.l"
return(XOR);
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 58 "kpasm.l"
return(IF);
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 59 "kpasm.l"
return(ELSE);
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 60 "kpasm.l"
return(MODULO);
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 61 "kpasm.l"
return(VIRGULE);
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 62 "kpasm.l"
return(FIN_OPCODE);
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 63 "kpasm.l"
return(LOCK);
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 64 "kpasm.l"
return(FREE);
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 65 "kpasm.l"
return(INITMEM);
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 66 "kpasm.l"
return(CHANGEMEM);
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 67 "kpasm.l"
return(TAILLE_DECRYPTEUR);
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 68 "kpasm.l"
return(WRITE8);
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 69 "kpasm.l"
return(WRITE16);
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 70 "kpasm.l"
return(WRITE32);
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 71 "kpasm.l"
{ yylval.entier=ATYPE_REGISTRE; return(ATYPE);};
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 72 "kpasm.l"
{ yylval.entier=ATYPE_ADRESSE; return(ATYPE);};
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 73 "kpasm.l"
{ yylval.entier=ATYPE_ENTIER; return(ATYPE);};
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 74 "kpasm.l"
{ yylval.entier=REG_EAX; return(REGISTRE);};
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 75 "kpasm.l"
{ yylval.entier=REG_EBX; return(REGISTRE);};
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 76 "kpasm.l"
{ yylval.entier=REG_ECX; return(REGISTRE);};
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 77 "kpasm.l"
{ yylval.entier=REG_EDX; return(REGISTRE);};
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 78 "kpasm.l"
{ yylval.entier=REG_ESI; return(REGISTRE);};
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 79 "kpasm.l"
{ yylval.entier=REG_EDI; return(REGISTRE);};
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 80 "kpasm.l"
{ yylval.entier=REG_EBP; return(REGISTRE);};
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 81 "kpasm.l"
{ yylval.entier=REG_ESP; return(REGISTRE);};
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 82 "kpasm.l"
{ yylval.entier=REG_EAX; return(UREGISTRE);};
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 83 "kpasm.l"
{ yylval.entier=REG_EBX; return(UREGISTRE);};
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 84 "kpasm.l"
{ yylval.entier=REG_ECX; return(UREGISTRE);};
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 85 "kpasm.l"
{ yylval.entier=REG_EDX; return(UREGISTRE);};
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 86 "kpasm.l"
{ yylval.entier=REG_ESI; return(UREGISTRE);};
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 87 "kpasm.l"
{ yylval.entier=REG_EDI; return(UREGISTRE);};
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 88 "kpasm.l"
{ yylval.entier=REG_EBP; return(UREGISTRE);};
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 89 "kpasm.l"
{ yylval.entier=REG_ESP; return(UREGISTRE);};
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 90 "kpasm.l"
return(REGLE_DEFAUT);
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 91 "kpasm.l"
return(RAW);
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 92 "kpasm.l"
{
char* debasm=strstr(yytext,"{")+1;
char* finasm=strstr(yytext,"}");
char* lasm=(char*)malloc((finasm-debasm+2)*sizeof(char));
strncpy(lasm,debasm,finasm-debasm);
lasm[finasm-debasm]='\0';
yylval.chaine=lasm;
return(ASM);
};
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 101 "kpasm.l"
{ yylval.entier = (int)yytext[6]-'0'; return(RNDINT) ; };
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 102 "kpasm.l"
{ yylval.entier = (int)yytext[7]-'0'; return(RNDMEM) ; };
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 103 "kpasm.l"
{ yylval.entier = (int)yytext[5]-'0'; return(LABEL) ; };
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 104 "kpasm.l"
{ yylval.entier = (int)yytext[7]-'0'; return(RNDREG) ; };
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 105 "kpasm.l"
{ yylval.entier = (int)yytext[6]-'0'; return(URNDREG) ; };
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 106 "kpasm.l"
{ yylval.entier = atoi(yytext);  return(NOMBRE) ; };
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 107 "kpasm.l"
{ sscanf(yytext,"%x",&yylval.entier);  return(NOMBRE) ; };
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 108 "kpasm.l"
{yylval.chaine = strdup(yytext); return ID;};
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 109 "kpasm.l"
ECHO;
	YY_BREAK
#line 1217 "lex.yy.c"
			case YY_STATE_EOF(INITIAL):
				yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_state_ptr = yy_state_buf;
	*yy_state_ptr++ = yy_current_state;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 197 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		*yy_state_ptr++ = yy_current_state;
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;

	register YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 197 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 196);
	if ( ! yy_is_jam )
		*yy_state_ptr++ = yy_current_state;

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	if ( c == '\n' )
		--yylineno;

	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	if ( c == '\n' )
		++yylineno;

	return c;
	}
#endif /* YY_NO_INPUT */

#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}



#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 109 "kpasm.l"
